---
abstract: 'Math is HARD (faster!)'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alt-Acme-Math-XS-External
no_index:
  directory:
    - t
    - inc
    - inc
    - lib/Acme
requires:
  perl: '5.008001'
version: v0.0.1
